
parameters:
    app_locales: en|fr|it
    
    # Default Assets
    assets_default_agent_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-batman.png'
    assets_default_customer_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-ironman.png'
    assets_default_helpdesk_profile_image_path: 'bundles/uvdeskcore/images/uv-avatar-uvdesk.png'

    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer

uvdesk:
    site_url: 'localhost:8001'
    upload_manager:
        id: Webkul\UVDesk\CoreBundle\FileSystem\UploadManagers\Localhost
    
    support_email:
        id: piyushgoeldigim@gmail.com
        name: Piyush goel
        mailer_id: mailer_9522
    
    # Default resources
    default:
        ticket:
            type: support
            status: open
            priority: low
        templates:
            email: mail.html.twig
